import create from 'zustand';
import books from './books.json';
export const bookStore = create(() => ({
  books: {
    data: books.data,
    page: 1,
    success: true,
    total: 1,
  },
  mybooks: [
    {
      title: 'React学习手册（第二版）',
      img: 'http://static.cainiaoapi.com/isbn/202233/16608081931e5805.jpg',
      author: '[美] 亚历克斯.班克斯，[美] 伊夫.波尔切洛，安道 著',
      isbn: '9787519856540',
      isbn10: '7519856542',
      publisher: '中国电力出版社',
      pubdate: '2021-06-01',
      pubplace: '',
      keyword: '',
      address: '本馆',
      pages: '376',
      price: '98.00',
      binding: '平装',
      edition: '',
      state: 'out',
      language: '',
      format: '16开',
      class: '',
      summary: '本书的主要内容有：理解JavaScript函数式编程的关键概念。深入了解React在浏览器中的运行机制。使用React组件创建应用的表现层。管理数据，减少花在调试应用上的时间。利用React钩子管理状态及获取数据。在单页应用中使用路由方案。学习站在服务器的角度上规划React应用。',
    },
    {
      title: 'Vue.js设计与实现',
      img: 'http://static.cainiaoapi.com/isbn/202233/1660807996c06bfb.jpg',
      author: '霍春阳（HcySunYang） 著',
      isbn: '9787115583864',
      isbn10: '7115583862',
      publisher: '人民邮电出版社',
      pubdate: '2022-01-01',
      pubplace: '',
      keyword: '',
      address: '本馆',
      pages: '501',
      price: '119.80',
      binding: '平装',
      edition: '',
      state: 'out',
      language: '',
      format: '16开',
      class: '',
      summary:
        '本书基于Vue.js 3，从规范出发，以源码为基础，并结合大量直观的配图，循序渐进地讲解Vue.js中各个功能模块的实现，细致剖析框架设计原理。全书共18章，分为六篇，主要内容包括：框架设计概览、响应系统、渲染器、组件化、编译器和服务端渲染等。通过阅读本书，对Vue.js 2/3具有上手经验的开发人员能够进一步理解Vue.js框架的实现细节，没有Vue.js使用经验但对框架设计感兴趣的前端开发人员，能够快速掌握Vue.js的设计原理。',
    },
    {
      title: 'JavaScript权威指南（原书第7版）',
      img: 'http://static.cainiaoapi.com/isbn/202233/166081158959dfd6.jpg',
      author: '（美）David Flanagan（弗兰纳根）',
      isbn: '9787111677222',
      isbn10: '7111677226',
      publisher: '机械工业出版社',
      pubdate: '2021-04-01',
      pubplace: '',
      keyword: '',
      address: '本馆',
      pages: '',
      price: '139.00',
      binding: '平装-胶订',
      edition: '',
      state: 'out',
      language: '',
      format: '16开',
      class: '',
      summary: '本书全面介绍了JavaScripti语言的核心，以及Web浏览器中实现的遗留和标准的DOM。全书分l7章，包括JavaScript简介；词法结构；类型、值和变量；表达式与操作符；语句；对象；数值等。',
    },
  ],
}));
